"""SQLAlchemy model for GeneratedCopy output from Copywriter Agent (AGT-07)."""

import uuid
from datetime import UTC, datetime

from sqlalchemy import Column, DateTime, Index, Integer, String, UniqueConstraint
from sqlalchemy.dialects.postgresql import JSONB

from backend.app.models.base import Base


class GeneratedCopy(Base):
    """
    Copy variants generated by the Copywriter Agent.

    Multi-tenant isolated. One row per (campaign, generation, asset_type, variant).
    """

    __tablename__ = "generated_copy"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    campaign_id = Column(String, nullable=False, index=True)
    tenant_id = Column(String, nullable=False, index=True)
    generation_id = Column(String, nullable=False, index=True)
    asset_type = Column(String, nullable=False)
    variant_id = Column(String, nullable=False)
    content = Column(JSONB, nullable=False)
    word_count = Column(Integer, nullable=False, default=0)
    model_used = Column(String, nullable=False)
    created_at = Column(
        DateTime(timezone=True),
        default=lambda: datetime.now(UTC),
        nullable=False,
    )

    __table_args__ = (
        UniqueConstraint(
            "campaign_id", "generation_id", "asset_type", "variant_id",
            name="uq_generated_copy_unique_variant",
        ),
        Index("ix_generated_copy_tenant_campaign", "tenant_id", "campaign_id"),
    )

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "campaign_id": self.campaign_id,
            "tenant_id": self.tenant_id,
            "generation_id": self.generation_id,
            "asset_type": self.asset_type,
            "variant_id": self.variant_id,
            "content": self.content,
            "word_count": self.word_count,
            "model_used": self.model_used,
            "created_at": self.created_at.isoformat() if self.created_at else None,
        }
