"""SQLAlchemy model for GeneratedCreative output from Creative Director Agent.

Stores creatives generated by AGT-06 including platform-specific variations,
validation status, and refinement attempts.
"""

from sqlalchemy import Column, String, Integer, DateTime, JSON, UniqueConstraint, Index, ForeignKey
from backend.app.models.base import Base

from sqlalchemy.dialects.postgresql import JSONB
from datetime import datetime, timezone
import uuid
class GeneratedCreative(Base):
    """
    Generated creative content from Creative Director Agent.

    Stores each generated creative with:
    - Multi-tenant isolation via tenant_id
    - Campaign and generation tracking
    - Platform-specific variations
    - Validation and refinement status
    - JSONB content for flexible schema
    """
    __tablename__ = "generated_creatives"

    # Primary key and identifiers
    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    campaign_id = Column(String, nullable=False, index=True)
    tenant_id = Column(String, nullable=False, index=True)
    generation_id = Column(String, nullable=False, index=True)

    # Platform and creative type
    platform = Column(String, nullable=False, index=True)
    creative_type = Column(String, nullable=False)

    # Content and metadata
    content = Column(JSONB, nullable=False)
    validation_status = Column(String, nullable=False)
    refinement_attempts = Column(Integer, default=0, nullable=False)

    # Timestamps
    created_at = Column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        nullable=False
    )
    updated_at = Column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
        nullable=False
    )

    # Unique constraint on creative combination
    __table_args__ = (
        UniqueConstraint(
            'campaign_id', 'generation_id', 'platform', 'creative_type',
            name='uq_generated_creatives_unique_creative'
        ),
    )

    def to_dict(self) -> dict:
        """Convert model to dictionary representation.

        Returns:
            Dictionary with all model fields
        """
        return {
            "id": self.id,
            "campaign_id": self.campaign_id,
            "tenant_id": self.tenant_id,
            "generation_id": self.generation_id,
            "platform": self.platform,
            "creative_type": self.creative_type,
            "content": self.content,
            "validation_status": self.validation_status,
            "refinement_attempts": self.refinement_attempts,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "updated_at": self.updated_at.isoformat() if self.updated_at else None,
        }
