"""SQLAlchemy model for GeneratedScript output from Scriptwriter Agent (AGT-08)."""

import uuid
from datetime import datetime, timezone

from sqlalchemy import Column, DateTime, Index, String, Text, UniqueConstraint
from backend.app.models.base import Base

from sqlalchemy.dialects.postgresql import JSONB
class GeneratedScript(Base):
    """
    Script variants generated by the Scriptwriter Agent.

    Multi-tenant isolated. One row per (campaign, generation, script_format, variant_label).
    """

    __tablename__ = "generated_scripts"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    campaign_id = Column(String, nullable=False, index=True)
    tenant_id = Column(String, nullable=False, index=True)
    generation_id = Column(String, nullable=False, index=True)
    script_format = Column(String, nullable=False)
    variant_label = Column(String, nullable=False)
    content = Column(JSONB, nullable=False)
    production_brief = Column(Text, nullable=False, default="")
    model_used = Column(String, nullable=False)
    created_at = Column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        nullable=False,
    )

    __table_args__ = (
        UniqueConstraint(
            "campaign_id", "generation_id", "script_format", "variant_label",
            name="uq_generated_script_unique_variant",
        ),
        Index("ix_generated_script_tenant_campaign", "tenant_id", "campaign_id"),
    )
