"""Schemas module for NTM application."""

from backend.app.schemas.budget_optimizer import (
    BudgetOptimizerResponse,
    BudgetShift,
    ChannelROISummary,
    OptimizationActionEnum,
    OptimizationReport,
    OptimizedActivation,
    PhaseROISummary,
    ROIAnalysis,
)
from backend.app.schemas.campaign import (
    CampaignConfirmRequest,
    CampaignCreateRequest,
    CampaignResponse,
    CampaignStatusEnum,
    CampaignUpdateRequest,
)
from backend.app.schemas.campaign_concept import (
    AudienceSegmentation,
    CampaignConcept,
    CampaignPhasing,
    ChannelRecommendation,
    MessageArchitecture,
    RiskFlags,
    ToneBoard,
)
from backend.app.schemas.media_plan import (
    Activation,
    AudienceSegmentEnum,
    BudgetSummary,
    ChannelEnum,
    ChannelSpend,
    ContingencyBreakdown,
    MediaPlanResponse,
    PhaseBreakdown,
    PhaseEnum,
)

__all__ = [
    "CampaignStatusEnum",
    "CampaignCreateRequest",
    "CampaignUpdateRequest",
    "CampaignConfirmRequest",
    "CampaignResponse",
    "CampaignConcept",
    "AudienceSegmentation",
    "ChannelRecommendation",
    "MessageArchitecture",
    "CampaignPhasing",
    "ToneBoard",
    "RiskFlags",
    "Activation",
    "BudgetSummary",
    "PhaseBreakdown",
    "ChannelSpend",
    "ContingencyBreakdown",
    "MediaPlanResponse",
    "ChannelEnum",
    "PhaseEnum",
    "AudienceSegmentEnum",
    "OptimizedActivation",
    "ROIAnalysis",
    "BudgetOptimizerResponse",
    "OptimizationReport",
    "PhaseROISummary",
    "ChannelROISummary",
    "BudgetShift",
    "OptimizationActionEnum",
]
